Development
xbreathoflife/gophermart pull request #1
Opened 2022-04-30 10:34 UTC by xbreathoflife

2022-05-03 21:09 UTC, ASPecherkin requested changes
оставил несколько комментариев

2022-05-03 21:09 UTC, ASPecherkin commented on cmd/gophermart/main.go
> +	"github.com/xbreathoflife/gophermart/config"
Мой совет - поставить golangci-lint и интегрировать в IDE  - тогда спиок импортов будет отформатироан одинково во всех файлах и проектах

2022-05-03 21:09 UTC, ASPecherkin commented on internal/app/core/service.go
> +		if resp.StatusCode == http.StatusTooManyRequests {
мое предлоение - использовать switch тут

2022-05-03 21:09 UTC, ASPecherkin commented on internal/app/storage/repository.go
> +type Storage interface {
тут есть момент - в Go не приятно делать большие интерфейсы, скорее делать более маленькие, разделённые по области применения бизнес логики

И дальше передавать такие в нужные функции - так ты ограничешь зону отвественности и проще будет писать тесты

2022-05-03 21:09 UTC, ASPecherkin commented on internal/app/storage/db.go
> +package storage
Моё предложение - разделить на отдельные файлы , и в него сгруппировать функции по области бизнес логики - заказ, пользователь, баланс

2022-05-03 21:09 UTC, ASPecherkin commented on internal/app/handler/handler.go
> +package handler
я бы разделил на отдельные файлы , в которых будут хендлеры сгруппированные по бизнес зонам / функциями

2022-05-05 17:04 UTC, xbreathoflife commented on cmd/gophermart/main.go
> +	"github.com/xbreathoflife/gophermart/config"
А что именно не так?

Я вроде бы прогнала, но он не стал ни на что жаловаться

2022-05-08 09:47 UTC, ASPecherkin approved these changes
Отличная работа!
Проблема с импортами ни на что не влияет, поэтому оставлю просто как комментарий

2022-05-08 09:47 UTC, ASPecherkin commented on cmd/gophermart/main.go
> +	"github.com/xbreathoflife/gophermart/config"
Воообще странно 

Обычно goimports/golangci-lint делят иморты по группам 

std 
пакеты проекта
всё остальное

2022-05-09 12:58 UTC, merged